<?php

/**
 * @file
 * Field context Test module.
 */

/**
 * Implements hook_help().
 */
function fieldcontext_test_help($path, $arg) {
  switch ($path) {
    case 'admin/help#fieldcontext_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>';
      $output .= t('Field context Test module provides sample data for Field context module test cases.');
      if (module_exists('simpletest')) {
        $output .= ' ' . t('See the <a href="@testing-url">Testing</a> page for available tests.', array('@testing-url' => url('admin/config/development/testing')));
      }
      $output .= '</p>';
      return $output;
  }
}

/**
 * Implements hook_fieldcontext_option_info().
 */
function fieldcontext_test_fieldcontext_option_info() {
  return array(
    'in valid %' => array(
      'title' => t('Invalid context (should not appear in field context selection)'),
    ),
    'price' => array(
      'title' => t('Price'),
      'group' => 'price',
      'weight' => 0,
    ),
    'creation_year' => array(
      'title' => t('Creation year'),
      'group' => 'year',
      'weight' => 1,
    ),
    'purchase_year' => array(
      'title' => t('Purchase year'),
      'group' => 'year',
      'weight' => 2,
    ),
  );
}

/**
 * Implements hook_fieldcontext_option_group_info().
 */
function fieldcontext_test_fieldcontext_option_group_info() {
  return array(
    'price' => array(
      'title' => t('Price group'),
      'weight' => 0,
    ),
    'year' => array(
      'title' => t('Year group'),
      'weight' => 1,
    ),
  );
}

/**
 * Alter predefined field context options.
 */
function fieldcontext_test_fieldcontext_options_alter(&$options) {
  $options['foobar'] = t('Foobar (this context has been added using alter function)');
}

/**
 * Alters allowed field context value pattern.
 */
function fieldcontext_test_fieldcontext_value_pattern_alter(&$pattern) {
  $pattern = '/^[A-Za-z0-9\-_$.]+$/';
}

/**
 * Alter allowed field context value pattern description.
 */
function fieldcontext_test_fieldcontext_value_pattern_description_text_alter(&$text) {
  $text = t('alphanumeric values, underscores, dashes or dollar sign');
}

/**
 * Promotes node to the front page if price value is equal or greater than 1000.
 */
function fieldcontext_test_node_presave($node) {
  // Get fields with context "price".
  $price_field_name = fieldcontext_get_field_name('price', 'node', $node->type);
  // Get price field values.
  $price_field_items = field_get_items('node', $node, $price_field_name);
  // Promote the node to front page if price value is equal or
  // greater than 1000.
  if (!empty($price_field_items[0]['value'])) {
    if ($price_field_items[0]['value'] >= 1000) {
      $node->promote = 1;
    }
  }
}
