<?php

/**
 * @file
 * Installation routines for Field context Test module.
 */

/**
 * Implements hook_install().
 */
function fieldcontext_test_install() {
  // Install test content types.
  fieldcontext_test_install_content_types();
  // Install test fields.
  fieldcontext_test_install_fields();
}

/**
 * Install content types for testing.
 */
function fieldcontext_test_install_content_types() {
  $t = get_t();

  // Define the node type.
  $content_types = array(
    'painting' => array(
      'type' => 'painting',
      'name' => $t('Painting'),
      'base' => 'node_content',
      'custom' => TRUE,
      'description' => $t('This is an example painting node content type.'),
      'body_label' => $t('Body'),
    ),
    'drawing' => array(
      'type' => 'drawing',
      'name' => $t('Drawing'),
      'base' => 'node_content',
      'custom' => TRUE,
      'description' => $t('This is an example drawing node content type.'),
      'body_label' => $t('Body'),
    ),
  );

  // Create test node content types.
  foreach ($content_types as $content_type) {
    // Set defaults.
    $content_type_defaults = node_type_set_defaults($content_type);
    // Add body field.
    node_add_body_field($content_type_defaults);
    // Save the content type.
    node_type_save($content_type_defaults);
    // Do not promote to the frontpage by default.
    variable_set('node_options_' . $content_type['type'], array('status'));
  }
}

/**
 * Install fields for testing.
 */
function fieldcontext_test_install_fields() {
  // Define context => field.
  $fields = array(
    'painting_price' => array(
      'field_name' => 'field_painting_price',
      'type' => 'text',
    ),
    'drawing_price' => array(
      'field_name' => 'field_drawing_price',
      'type' => 'text',
    ),
    'creation_year' => array(
      'field_name' => 'field_creation_year',
      'type' => 'number_integer',
    ),
    'purchase_year' => array(
      'field_name' => 'field_purchase_year',
      'type' => 'number_integer',
    ),
  );

  // Create fields.
  foreach ($fields as $field) {
    field_create_field($field);
  }

  // Define instances.
  $instances = array(
    'node_painting_context_field_painting_price' => array(
      'field_name' => 'field_painting_price',
      'entity_type' => 'node',
      'bundle' => 'painting',
      'label' => 'Price',
      'description' => 'Price of the painting.',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'price',
      ),
      'widget' => array(
        'type' => 'textfield',
      ),
    ),
    'node_drawing_context_field_drawing_price' => array(
      'field_name' => 'field_drawing_price',
      'entity_type' => 'node',
      'bundle' => 'drawing',
      'label' => 'Price',
      'description' => 'Price of the drawing.',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'price',
      ),
      'widget' => array(
        'type' => 'textfield',
      ),
    ),
    'node_painting_context_field_creation_year' => array(
      'field_name' => 'field_creation_year',
      'entity_type' => 'node',
      'bundle' => 'painting',
      'label' => 'Creation year',
      'description' => 'The year in which painting was created.',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'creation_year',
      ),
      'widget' => array(
        'type' => 'number',
      ),
    ),
    'node_drawing_context_field_creation_year' => array(
      'field_name' => 'field_creation_year',
      'entity_type' => 'node',
      'bundle' => 'drawing',
      'label' => 'Creation year',
      'description' => 'The year in which drawing was created.',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'creation_year',
      ),
      'widget' => array(
        'type' => 'number',
      ),
    ),
    'node_drawing_context_field_purchase_year' => array(
      'field_name' => 'field_purchase_year',
      'entity_type' => 'node',
      'bundle' => 'drawing',
      'label' => 'Purchase year',
      'description' => 'The year in which drawing was purchased.',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'purchase_year',
      ),
      'widget' => array(
        'type' => 'number',
      ),
    ),
  );

  // Create instances.
  foreach ($instances as $instance) {
    // Create an instance.
    field_create_instance($instance);
  }
}

/**
 * Implements hook_uninstall().
 */
function fieldcontext_test_uninstall() {
  foreach (array('painting', 'drawing') as $type) {
    // Remove content type.
    node_type_delete($type);
    // Remove variables.
    variable_del('node_options_' . $type);
  }
}
