<?php

/**
 * @file
 * Installation routines for Field context Test module.
 */

/**
 * Implements hook_install().
 */
function fieldcontext_test_install() {
  // Install test content types.
  fieldcontext_test_install_content_types();
  // Install test fields.
  fieldcontext_test_install_fields();
}

/**
 * Install content types for testing.
 */
function fieldcontext_test_install_content_types() {
  $t = get_t();

  // Define the node type.
  $content_types = array(
    'wine_context' => array(
      'type' => 'wine_context',
      'name' => $t('Wine (Context)'),
      'base' => 'node_content',
      'description' => $t('This is an example wine node content type.'),
      'body_label' => $t('Body'),
    ),
    'beer_context' => array(
      'type' => 'beer_context',
      'name' => $t('Beer (Context)'),
      'base' => 'node_content',
      'description' => $t('This is an example beer node content type.'),
      'body_label' => $t('Body'),
    ),
  );

  // Create test node content types.
  foreach ($content_types as $content_type) {
    // Set defaults.
    $content_type_defaults = node_type_set_defaults($content_type);
    // Add body field.
    node_add_body_field($content_type_defaults);
    // Save the content type.
    node_type_save($content_type_defaults);
  }
}

/**
 * Install fields for testing.
 */
function fieldcontext_test_install_fields() {
  // Define context => field.
  $fields = array(
    'brand' => array(
      'field_name' => 'field_brand',
      'type' => 'text',
    ),
    'year' => array(
      'field_name' => 'field_year',
      'type' => 'number_integer',
    ),
    'purchase_year' => array(
      'field_name' => 'field_purchase_year',
      'type' => 'number_integer',
    ),
  );

  // Create fields.
  foreach ($fields as $field) {
    field_create_field($field);
  }

  // Define instances.
  $instances = array(
    'node_wine_context_field_brand' => array(
      'field_name' => 'field_brand',
      'entity_type' => 'node',
      'bundle' => 'wine_context',
      'label' => 'Brand',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'brand',
      ),
      'widget' => array(
        'type' => 'textfield',
      ),
    ),
    'node_beer_context_field_brand' => array(
      'field_name' => 'field_brand',
      'entity_type' => 'node',
      'bundle' => 'beer_context',
      'label' => 'Brand',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'brand',
      ),
      'widget' => array(
        'type' => 'textfield',
      ),
    ),
    'node_wine_context_field_year' => array(
      'field_name' => 'field_year',
      'entity_type' => 'node',
      'bundle' => 'wine_context',
      'label' => 'Production year',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'year',
      ),
      'widget' => array(
        'type' => 'number',
      ),
    ),
    'node_beer_context_field_year' => array(
      'field_name' => 'field_year',
      'entity_type' => 'node',
      'bundle' => 'beer_context',
      'label' => 'Production year',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'year',
      ),
      'widget' => array(
        'type' => 'number',
      ),
    ),
    'node_beer_context_field_purchase_year' => array(
      'field_name' => 'field_purchase_year',
      'entity_type' => 'node',
      'bundle' => 'beer_context',
      'label' => 'Purchase year',
      'settings' => array(
        'user_register_form' => 1,
        // Define field context for this instance.
        'fieldcontext' => 'year1',
      ),
      'widget' => array(
        'type' => 'number',
      ),
    ),
  );

  // Create instances.
  foreach ($instances as $instance) {
    // Create an instance.
    field_create_instance($instance);
  }
}
